### ISSUE TITLE
Implements DNS over proxy

### ISSUE THREAD

**Issue by iSynex** [h12w/socks#17]
Add support for DNS resolution over SOCKS4 / SOCKS5

**Comment by h12w** [comment]
SOCKS4 does not support it, but SOCKS4a and SOCKS5 already have it:

* https://github.com/h12w/socks/blob/master/socks4.go#L45
* https://github.com/h12w/socks/blob/master/socks5.go#L80

The next question is if the HTTP client using a socks proxy as a TCP transport layer will take advantage of this and pass a hostname instead of an IP address.

TBH, I don't know but it's not a concern of this package either.
